version: "3"

dotenv:
  - .env

tasks:

  # compile:
  #   env:
  #     GOOS: linux
  #   cmds:
  #     - go build -o ./bin/appapi ./cmd/api/
  #     - go build -o ./bin/appinfo ./cmd/info/
  #     - go build -o ./bin/applogin ./cmd/login/

  build:
    cmds:
      - docker build -f ./cmd/api-service/Dockerfile -t gleb1337/api-app:latest .
      - docker build -f ./cmd/info-service/Dockerfile -t gleb1337/info-app:latest .
      - docker build -f ./cmd/login-service/Dockerfile -t gleb1337/login-app:latest .
      - docker build -f ./cmd/root-service/Dockerfile -t gleb1337/root-app:latest .

  push:
    cmds:
      - docker push gleb1337/api-app:latest 
      - docker push gleb1337/info-app:latest 
      - docker push gleb1337/login-app:latest 
      - docker push gleb1337/root-app:latest 

  deploy:
    cmds:
      - kubectl apply -n sirius -f ./deployments/k8s/api/
      - kubectl apply -n sirius -f ./deployments/k8s/info/
      - kubectl apply -n sirius -f ./deployments/k8s/login/
      - kubectl apply -n sirius -f ./deployments/k8s/root/
      - kubectl apply -n sirius -f ./deployments/k8s/ingress.yaml

  release:
    cmds:
    #  - task: compile
      - task: build
      - task: deploy